In Go, when a program encounters a segmentation fault or encounters a condition that triggers a panic, 
Go will automatically print a stack trace to stderr. This stack trace includes information about where the panic occurred, including the file name, line number, and function name for each stack frame.

## runtime/debug package

The `runtime/debug` package in Go provides various debugging support functionalities, such as:

- Obtaining a stack trace
- Controlling the garbage collector
- Printing memory statistics
- Reading and setting the build information
- Retrieving the function's name and entry point

To obtain a stack trace of the current goroutine, you can use the `debug.Stack()` function, which returns a byte slice with the stack trace formatted as a string:

```golang
package main

import (
	"fmt"
	"runtime/debug"
)

func main() {
	stackTrace := debug.Stack()
	fmt.Printf("%s\n", stackTrace)
}
```
When you run this program, you will see the stack trace of the main goroutine:

```golang
$ go run main.go
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.main()
	/path/to/main.go:9 +0x5f
```

### Example1
```golang
package main

import (
	"fmt"
)

func recursiveFunction(n int) {
	if n <= 0 {
		// Intentional bug: accessing index -1 of an empty slice
		slice := []int{}
		_ = slice[-1]
		return
	}
	recursiveFunction(n - 1)
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Recovered from panic:")
			fmt.Println(r)
			fmt.Println("Stack trace:")
			fmt.Printf("%s", debug.Stack())
		}
	}()

	// Call the recursive function with an initial value
	recursiveFunction(5)
	fmt.Println("Program continues execution...")
}
```
When we run this program, it will panic due to the bug, but we've added a deferred function that recovers from the panic and prints a stack trace using debug.Stack(). 
This will help us identify exactly where in the recursive function the panic occurred and trace the sequence of function calls that led to the panic.

### Example2

```golang
package main

import (
	"fmt"
	"runtime/debug"
)

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Recovered from panic:", r)
			debug.PrintStack()
		}
	}()

	// Simulate a runtime error by accessing an out-of-bounds index
	var arr []int
	fmt.Println(arr[10])
}
```
## Reference
https://reintech.io/blog/introduction-to-gos-runtime-debug-package




